// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jrouY0CB1E5P0dxmdhpDLLiwM02O_8Q',
    appId: '1:496482390503:web:b272207372ec0b6e8eed42',
    messagingSenderId: '496482390503',
    projectId: 'cadmir-erp',
    authDomain: 'cadmir-erp.firebaseapp.com',
    storageBucket: 'cadmir-erp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxomwSrchIBLsVoKpDY9BkQsxY7vOSxCU',
    appId: '1:496482390503:android:3cdee9c61fac8b8c8eed42',
    messagingSenderId: '496482390503',
    projectId: 'cadmir-erp',
    storageBucket: 'cadmir-erp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jrouY0CB1E5P0dxmdhpDLLiwM02O_8Q',
    appId: '1:496482390503:web:24669b3b4837d5628eed42',
    messagingSenderId: '496482390503',
    projectId: 'cadmir-erp',
    authDomain: 'cadmir-erp.firebaseapp.com',
    storageBucket: 'cadmir-erp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgAzD8zKWp5oApKfRLdBnylifRPUNdK4',
    appId: '1:496482390503:ios:978e1d259611139d8eed42',
    messagingSenderId: '496482390503',
    projectId: 'cadmir-erp',
    storageBucket: 'cadmir-erp.firebasestorage.app',
    iosBundleId: 'com.example.cadmir',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgAzD8zKWp5oApKfRLdBnylifRPUNdK4',
    appId: '1:496482390503:ios:978e1d259611139d8eed42',
    messagingSenderId: '496482390503',
    projectId: 'cadmir-erp',
    storageBucket: 'cadmir-erp.firebasestorage.app',
    iosBundleId: 'com.example.cadmir',
  );

}